#!/bin/bash
# Set environment variables (in a secure way, not hardcoded in the script in real scenarios)
export DOMAIN=csadev
export WORKSPACE=leaf
export TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJaRDV1MDdWZnoyOWtXd1hXYWozT1ZHLS1HUEFGcmcwVV94RzgwWG1Ja3dZIn0.eyJleHAiOjE3MTkzNDc0OTUsImlhdCI6MTcxOTM0NTY5NSwianRpIjoiNTk1NGJjZmUtNmZmYy00MDhjLWJiNTAtYzBiYWM3ZjIyZjQxIiwiaXNzIjoiaHR0cHM6Ly9rZXljbG9hay5jc2FkZXYuZGVjLmVhcnRoZGFpbHkuY29tL3JlYWxtcy9tYXN0ZXIiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiMDkxYWJlZDEtNGY1NC00YTU3LWFhOTMtMzQ5NjhmMzY5NzQxIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoid3MtbGVhZiIsInNlc3Npb25fc3RhdGUiOiIwZTFkZTFmZC03YWI5LTQzMDktYTRmZC0wNTk1MzIzNjRhMjYiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMtbWFzdGVyIiwib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsInNpZCI6IjBlMWRlMWZkLTdhYjktNDMwOS1hNGZkLTA1OTUzMjM2NGEyNiIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoibGVhZiIsImdpdmVuX25hbWUiOiIiLCJmYW1pbHlfbmFtZSI6IiJ9.ncZuqcJDD_m2vkJGYFOK6dC2hkl5MB_fxVQMb1LjDD9UpFvBKvg0U0XrACA21t043gmswcVU-XLCug_GAIZyFBux7H6Jom7RSaomdj4wUgjkms8ojIx3ng9gWdTQPBfsJwzLC7l9qO5ddZaO34J9IB531VehZRTy8PhceTOXR8zjrny-zbdJPx-l64wAIl09CMV_kMYPmrzr3a6IV1BL1XNgKqA01PYX03p_E-tg-ovHGcyC2My2ZTgJ5WphJiklrRv4idE4YToViE_5F8mv5sXnmxOUgldRdNI5EiA1t_yIKNZpotfspH2G_Zjc5ioRP35_eS96k5tO-sFhFD-r5g

curl --location https://workspace-api.${DOMAIN}.dec.earthdaily.com/workspaces/ws-${WORKSPACE} --header "Authorization: Bearer ${TOKEN}"


